# Generated by Django 5.0.3 on 2024-03-04 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_rename_employee_employees'),
        ('samples', '0002_alter_samples_drawing_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Collection', 'Collection'), ('Return', 'Return'), ('Other', 'Other')], max_length=20)),
                ('collection_date', models.DateTimeField(unique=True)),
                ('production_order', models.CharField(blank=True, max_length=50, null=True)),
                ('return_date', models.DateTimeField(unique=True)),
                ('storage_place', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.samples')),
            ],
        ),
    ]
