# Generated by Django 5.0.3 on 2024-03-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleoperation',
            name='collection_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sampleoperation',
            name='operation_type',
            field=models.CharField(choices=[('Collection', 'Collection'), ('Return', 'Return')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sampleoperation',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
