# Generated by Django 5.0.3 on 2024-03-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_sampleoperation_collection_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleoperation',
            old_name='collection_date',
            new_name='operation_date',
        ),
        migrations.RemoveField(
            model_name='sampleoperation',
            name='return_date',
        ),
    ]
