# Generated by Django 5.0.3 on 2024-03-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_collection_date_sampleoperation_operation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleoperation',
            name='operation_date',
            field=models.DateTimeField(error_messages={'required': 'Please fill in this field.'}),
        ),
    ]
