# Generated by Django 5.0.3 on 2024-03-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_employee_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Employees', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
