# Generated by Django 5.0.3 on 2024-03-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employees_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(choices=[('quality', 'quality'), ('projects', 'projects'), ('tool-house', 'tool-house'), ('technical', 'technical'), ('other', 'other')], max_length=20),
        ),
    ]
