# Generated by Django 5.0.3 on 2024-03-04 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(99999)])),
                ('part_name', models.CharField(max_length=255, unique=True)),
                ('drawing_number', models.CharField(max_length=20, unique=True)),
                ('drawing_revision', models.CharField(max_length=20, unique=True)),
                ('client', models.CharField(max_length=125)),
                ('trial_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Not approved', 'Not approved')], default='Not approved', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('storage_place', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
