# Generated by Django 5.0.3 on 2024-03-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_alter_samples_drawing_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samples',
            options={'verbose_name': 'Samples', 'verbose_name_plural': 'Samples'},
        ),
    ]
